[package]
name = "phantom-client"
version.workspace = true
edition.workspace = true

[lib]
name = "phantom_client"
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
phantom-proto = { path = "../packet-proto" }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tokio-tungstenite = { version = "0.21", default-features = false, features = ["handshake"] }
futures-util = { version = "0.3", default-features = false, features = ["sink"] }
url = "2"
http = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
clap = { version = "4", features = ["derive", "env"] }
rand = "0.8"
jni = "0.22.4"
lazy_static = "1.5.0"
socket2 = "0.6.3"
tokio-rustls = { version = "0.26", default-features = false, features = ["logging", "ring", "tls12"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "logging", "std", "tls12"] }
webpki-roots = "0.26"
rustls-pki-types = "1"
rustls-webpki = { version = "0.103.12", default-features = false, features = ["ring", "std"] }
libc = "0.2"
tun2socks = "0.1.10"
